### ISSUE TITLE
Dynamic profile picture in NavigationDrawerWithAccountsAndFullHeightActivity 

### ISSUE THREAD

**Issue by adityamhatre** [DenisMondon/material-design-library#24]
Greetings.
I am currently developing an application which allows the user to log in and ser their own profile picture. 
I am using your library, since it's great and offers so many stuff. 
Consider this scenario. 
When app first launches. .The static profile pic will be shown in navigation drawer ...but after login the navigation drawer account picture should be updated. 
I have all the bitmap ready for displaying. ..which I retrieve from the server.
And is it possible that the ImageView in the abovementioned activity can be changed to FeedImageView or NetworkImageView from volley library ?
Could be great since it can show a loading indicator on the image ..

This is how I am asking for.
![device-2015-07-15-012538 - copy](https://cloud.githubusercontent.com/assets/13261128/8683617/94233250-2a91-11e5-9d34-0d0502044aea.png)

**Comment by adityamhatre** [comment]
anyone?

**Comment by DenisMondon** [comment]
Sorry for the late...
It is not possible for now, I will work on it soon ;)

Thank you!

Denis

**Comment by adityamhatre** [comment]
ohhh...alright...
i solved it using an alternative approach..

```
@Override
    public NavigationDrawerAccountsHandler getNavigationDrawerAccountsHandler() {
        if (AppController.getInstance().getLoggedIn())
            return new NavigationDrawerAccountsHandler(this).addAccount(AppController.getInstance().getUserInfo().getUser(), AppController.getInstance().getUserInfo().getEmail(), R.drawable.profile1, R.drawable.navigation_drawer_bg).enableSmallAccountsLayout(false);
        else
            return new NavigationDrawerAccountsHandler(this).addAccount("User", "Not logged in", R.drawable.profile1, R.drawable.navigation_drawer_bg).enableSmallAccountsLayout(false);
    }
```

for login..i used a different activity..when i start loginactivity, the current activity is finished and login actiivty starts...then after login..a flag is triggered...and mainactivity starts again and sets the drawer accoridngly..

A workaround though..  :)

**Comment by adityamhatre** [comment]
though the netowrk image thing still remains...can u help me with that?

**Comment by adityamhatre** [comment]
Help please ...

**Comment by adityamhatre** [comment]
any workaround ?

**Comment by adityamhatre** [comment]
@Denis ?

**Comment by adityamhatre** [comment]
@Denismondon

**Comment by DenisMondon** [comment]
Hey sorry,

Can you explain the problem with the network image?
Thanks

**Comment by adityamhatre** [comment]
Please see the above screenshots....
Basically I get a Image URL from a webservice and I want to display that image in the profile picture..

**Comment by DenisMondon** [comment]
Ok sorry, my bad...
Tomorrow, I will release the new version of the lib, and you will be able to do this:
```java
.addAccount("username", "email", "http://picture url", R.drawable.navigation_drawer_bg);
```
It is already implemented. I just have to create the release :)

Denis

**Comment by adityamhatre** [comment]
Great !!
You rock man !

**Comment by adityamhatre** [comment]
@DenisMondon  
the release please??

**Comment by DenisMondon** [comment]
Hi!

You can now write this:
```java
.addAccount("username", "email", "http://picture url", R.drawable.navigation_drawer_bg);
```

**Comment by adityamhatre** [comment]
thanks

**Comment by adityamhatre** [comment]
it's not working..app is crashing.


08-02 02:24:23.298  23032-23032/com.thelogicalcoder.viazene E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.thelogicalcoder.viazene, PID: 23032
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.thelogicalcoder.viazene/com.thelogicalcoder.viazene.Activities.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2548)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2607)
            at android.app.ActivityThread.access$900(ActivityThread.java:174)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5756)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.thelogicalcoder.viazene.Activities.MainActivity.getNavigationDrawerAccountsHandler(MainActivity.java:83)
            at com.blunderer.materialdesignlibrary.activities.NavigationDrawerActivity.showAccountsLayout(NavigationDrawerActivity.java:377)
            at com.blunderer.materialdesignlibrary.activities.NavigationDrawerActivity.defineListTop(NavigationDrawerActivity.java:183)
            at com.blunderer.materialdesignlibrary.activities.NavigationDrawerActivity.onCreate(NavigationDrawerActivity.java:139)
            at com.thelogicalcoder.viazene.Activities.MainActivity.onCreate(MainActivity.java:169)
            at android.app.Activity.performCreate(Activity.java:5619)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2512)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2607)
            at android.app.ActivityThread.access$900(ActivityThread.java:174)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5756)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by adityamhatre** [comment]
it's not working..app is crashing.
08-02 02:39:23.178 682-682/com.thelogicalcoder.viazene E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.thelogicalcoder.viazene, PID: 682
java.lang.ClassCastException: com.bumptech.glide.request.target.SquaringDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
at com.blunderer.materialdesignlibrary.views.RoundedImageView.onDraw(RoundedImageView.java:35)
at android.view.View.draw(View.java:15534)
at android.view.View.getDisplayList(View.java:14428)
at android.view.View.getDisplayList(View.java:14470)
at android.view.View.draw(View.java:15248)
at android.view.ViewGroup.drawChild(ViewGroup.java:3366)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
at android.view.View.getDisplayList(View.java:14423)
at android.view.View.getDisplayList(View.java:14470)
at android.view.View.draw(View.java:15248)
at android.view.ViewGroup.drawChild(ViewGroup.java:3366)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
at android.view.View.getDisplayList(View.java:14423)
at android.view.View.getDisplayList(View.java:14470)
at android.view.View.draw(View.java:15248)
at android.view.ViewGroup.drawChild(ViewGroup.java:3366)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
at android.view.View.getDisplayList(View.java:14423)
at android.view.View.getDisplayList(View.java:14470)
at android.view.View.draw(View.java:15248)
at android.view.ViewGroup.drawChild(ViewGroup.java:3366)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
at android.view.View.getDisplayList(View.java:14423)
at android.view.View.getDisplayList(View.java:14470)
at android.view.View.draw(View.java:15248)
at android.view.ViewGroup.drawChild(ViewGroup.java:3366)
at android.widget.ListView.drawChild(ListView.java:3418)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
at android.widget.AbsListView.dispatchDraw(AbsListView.java:2991)
at android.widget.ListView.dispatchDraw(ListView.java:3413)
at android.view.View.draw(View.java:15537)
at android.widget.AbsListView.draw(AbsListView.java:5775)
at android.view.View.getDisplayList(View.java:14428)
at android.view.View.getDisplayList(View.java:14470)
at android.view.View.draw(View.java:15248)
at android.view.ViewGroup.drawChild(ViewGroup.java:3366)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
at android.view.View.draw(View.java:15537)
at android.view.View.getDisplayList(View.java:14428)
at android.view.View.getDisplayList(View.java:14470)
at android.view.View.draw(View.java:15248)
at android.view.ViewGroup.drawChild(ViewGroup.java:3366)
at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
at android.view.View.getDisplayList(View.java:14423)
at android.view.View.getDisplayList(View.java:14470)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
at android.view.View.getDisplayList(View.java:14365)
at android.view.View.getDisplayList(View.java:14470)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
at android.view.View.getDisplayList(View.java:14365)
at android.view.View.getDisplayList(View.java:14470)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
at android.view.View.getDisplayList(View.java:14365)
at android.view.View.getDisplayList(View.java:14470)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
at android.view.View.getDisplayList(View.java:14365)
at android.view.View.getDisplayList(View.java:14470)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
at android.view.View.getDisplayList(View.java:14365)
at android.view.View.getDisplayList(View.java:14470)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
at android.view.View.getDisplayList(View.java:14365)
at android.view.View.getDisplayList(View.java:14470)
at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1596)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1469)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:

**Comment by adityamhatre** [comment]
never mind...solved it

added this method in Accounts.java
```java 
private BitmapTypeRequest<String> mPictureUrl;
public BitmapTypeRequest<String> getPictureUrl() {
        return mPictureUrl;
 }
```

added this method in ListItem.java
```java
private BitmapTypeRequest<String> mIconUrlB;
public void setIcon(BitmapTypeRequest<String> iconUrl) {
        mUseIconResource = false;
        mUseIconUrl = true;
        mIconUrlB = iconUrl;
}
```

**Comment by DenisMondon** [comment]
Oh my god! My bad.
I completly forgot to commit this fix!
You can delete your own fix. I had just changed the RoundedImageView.java file.

So just change the current version to 2.0.2!

Sorry again...

Denis

**Comment by adityamhatre** [comment]
Thank you.
Happy to help :)
You just changed the RoundedImageView. Java file right ?

**Comment by adityamhatre** [comment]
Is it possible to show a loading indicator on the rounded image view until the image is fetched from url ?

**Comment by DenisMondon** [comment]
Yeah I will try to do it today ;) I let you know

**Comment by adityamhatre** [comment]
btw great work..
i studied your library....exquisite work ! :+1:

**Comment by DenisMondon** [comment]
Thank you :)
It is ok. With the 2.0.3 version, there is a progress bar for accounts profile pictures :)

Tell me if you see some errors ;)

Denis

**Comment by adityamhatre** [comment]
One issue...
If the image is transparent. ..I cam still see the progress bar loading....maybe make the visibility to gone after image is loaded ?

**Comment by DenisMondon** [comment]
Oh, it should set the visibility to invisible but maybe I forgot somewhere... I will see tomorrow if I can :)

**Comment by DenisMondon** [comment]
You sure?
Are you using Small Acounts Layout or the normal one?
How many accounts have you?

**Comment by adityamhatre** [comment]
normal one.....
only one account...

**Comment by DenisMondon** [comment]
I really don't see the bug :( Here is a screen with only one account and the normal Accounts Layout with a transparent image: ![device-2015-08-06-204905](https://cloud.githubusercontent.com/assets/1906100/9120456/9f78f962-3c7c-11e5-8c36-3853e135cd95.png)
Can you show yours? And maybe use the 2.0.4 version.

**Comment by adityamhatre** [comment]
![screenshot_2015-08-07-14-57-33(https://cloud.githubusercontent.com/assets/13261128/9132927/ce6244f2-3d14-11e5-8182-0da9a41ae830.png)

**Comment by DenisMondon** [comment]
Strange... You are using the 2.0.4 version?
