### ISSUE TITLE
How do i inflate a header or footer to the listview fragment or the listview activity

### ISSUE THREAD

**Issue by root1** [DenisMondon/material-design-library#27]
i have tried to use my custom listview layout but im getting a nullpointer exception when i try inflating a header to the listview. Is there any way i can achieve this without having to create a totatly different fragment

**Comment by DenisMondon** [comment]
Hi root1 :)

It it easy: in your Activity that extends ListViewActivity, add this onCreate method:

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mListView.addHeaderView(your_header_view);
    }
```

Denis

**Comment by root1** [comment]
Ok thanks man, i will give it a try

**Comment by root1** [comment]
Well i tried your suggestion but it on the ListViewFragment and put the addHeaderView in the onActivityCreated seems setAdapter would already have been called by then so its giving a nullpointer exception

**Comment by DenisMondon** [comment]
Hi

I don't understand why you're getting this nullpointerexception because I have tested with a ListViewActivity and a ListViewFragment, and it works really great!

In your ListViewFragment, just write this:
```java
    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        TextView view = new TextView(getActivity());
        view.setText("sdfsdfs");
        mListView.addHeaderView(view);
    }
```

If it doesn't work, show me your code ;)

**Comment by root1** [comment]
``` public class ProductsListFragment
        extends com.blunderer.materialdesignlibrary.fragments.ListViewFragment {

    public ProductListViewListAdapter productListViewListAdapter;
    public List<Product> products;

    @Override
    public ListAdapter getListAdapter() {

        products = new ArrayList<>();
       
        products.add(new Product("Silver Plated Rings", "$200 / Piece", "Image", "Astro Mobile"));
        productListViewListAdapter = new ProductListViewListAdapter(getActivity(), products);
        return productListViewListAdapter;

    }

    @Override
    public boolean useCustomContentView() {
        return false;
    }

    @Override
    public int getCustomContentView() {
        return 0;
    }

    @Override
    public boolean pullToRefreshEnabled() {
        return true;
    }

    @Override
    public int[] getPullToRefreshColorResources() {
        return new int[]{R.color.primary};
    }
    @Override
    public void onRefresh() {
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                setRefreshing(false);
            }

        }, 2000);
    }

    @Override
    public void onItemClick(AdapterView<?> adapterView, View view, int position, long l) {
        startActivity(new Intent(getActivity(), ProductViewNormal.class));
    }

    @Override
    public boolean onItemLongClick(AdapterView<?> adapterView, View view, int position, long l) {
        return false;
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        View view = View.inflate(getActivity(), R.layout.contact_header, null);
        TextView text = (TextView)view.findViewById(R.id.likes_num);
        text.setText("1928u8412837421834");
        mListView.addHeaderView(view);
    }
}```

AND THIS IS THE ERROR LOG

``` java.lang.RuntimeException: Unable to start activity ComponentInfo{paywallet.paywallet/paywallet.paywallet.NavigationDrawerWithAccountsAndFullHeightActivity}: java.lang.IllegalStateException: Cannot add header view to list -- setAdapter has already been called.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2067)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2092)
            at android.app.ActivityThread.access$600(ActivityThread.java:133)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4794)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Cannot add header view to list -- setAdapter has already been called.
            at android.widget.ListView.addHeaderView(ListView.java:255)
            at android.widget.ListView.addHeaderView(ListView.java:284)
            at products.ProductsListFragment.onActivityCreated(ProductsListFragment.java:101)
            at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1797)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:979)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
            at android.app.Activity.performStart(Activity.java:5057)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2040)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2092)
            at android.app.ActivityThread.access$600(ActivityThread.java:133)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4794)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by root1** [comment]
```Cannot add header view to list -- setAdapter has already been called.```
Thats the error there

**Comment by DenisMondon** [comment]
Ok, I figured out the problem. :D
It is because you have a old android version (< 5.0??).
I tested on my OnePlus One (5.0.2) and it works fine and on my Nexus 4 (4.2.2) it crashes :'(

I will see what I can do (I will surely add a patch in the next release).

Denis

**Comment by root1** [comment]
cheers

**Comment by DenisMondon** [comment]
Hi!

You can now add this in your ListViewFragment:
```java
    @Override
    public View getListViewHeaderView() {
        TextView tv = new TextView(getActivity());
        tv.setText("header");
        return tv;
    }

    @Override
    public View getListViewFooterView() {
        TextView tv = new TextView(getActivity());
        tv.setText("footer");
        return tv;
    }
```

Hope it helped!

Denis

**Comment by root1** [comment]
Thanks man i will try it out
