### ISSUE TITLE
Resources$NotFoundException on API < Lollipop

### ISSUE THREAD

**Issue by antony7777** [DenisMondon/material-design-library#47]
Hi, :-)

Tried using the library. But when running on KitKat, I got into resource not found exceptoin:

java.lang.RuntimeException: Unable to start activity ComponentInfo{test.testapp/test.testapp.MdlActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f020065
...<snip>
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020065
at android.content.res.Resources.getValue(Resources.java:1123)
at android.content.res.Resources.getDrawable(Resources.java:698)
at com.blunderer.materialdesignlibrary.models.Account.setPicture(Account.java:51)
at com.blunderer.materialdesignlibrary.handlers.NavigationDrawerAccountsHandler.addAccount(NavigationDrawerAccountsHandler.java:30)
...<snip>

The resource I access is there. The same app works on higher API level. 
The code that throw exception is:

    public void setPicture(Context context, int pictureResource) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            mPictureResource = context.getDrawable(pictureResource);
        } else mPictureResource = context.getResources().getDrawable(pictureResource); // this line
    }

Any idea why this is happening? :-)

ps. when I try to run your sample, I got build error:
Error:(35, 8) error: MainActivity is not abstract and does not override abstract method enableActionBarShadow() in AActivity

Thanks for sharing this library! :-)

**Comment by antony7777** [comment]
Found the problem.. :-)
The resources were in drawable-v21 folder. Dunno how that happened.. Copied them to drawable folder, then it's running fine.. :-)
